//! Session alias resolution.
//!
//! `resolve_alias(name)` maps a human-readable session title alias to its
//! canonical UUID `sid` by looking up `titles.tsv`.
//!
//! ## Spec reference (N6 / §2 Arg parsing)
//!
//! When `-r`/`--resume <name>` is given and `<name>` is **not** UUID-shaped,
//! `csm` treats it as a title alias and calls `resolve_alias` to obtain the
//! real session UUID.  An unknown alias is a **hard error** — the binary must
//! not silently fall back to starting a fresh session (the user named a specific
//! session; ignoring that would discard their intent).
//!
//! ## `titles.tsv` format
//!
//! Generated by the session scanner; each line is tab-delimited:
//! ```text
//! <title_alias>\t<sid>\t<mtime_epoch>
//! ```
//! Lines starting with `#` are comments and are ignored.
//!
//! Lookup is **case-insensitive**, first-match wins (file is written
//! newest-first by mtime, so the most recent match is returned).
//!
//! ## Phase 0
//!
//! The body of `resolve_alias` is `unimplemented!()` — the `titles.tsv` writer
//! lives in `session/scan.rs` (Phase 5).  The signature and error type are final.

use crate::paths;
use thiserror::Error;

/// Errors from alias resolution.
#[derive(Debug, Error)]
pub enum AliasError {
    /// The alias was not found in `titles.tsv`.  This is a hard error per spec N6.
    #[error("unknown session alias {alias:?} — not found in titles.tsv (use a UUID or a known title)")]
    NotFound { alias: String },

    /// `titles.tsv` could not be read (I/O error).
    #[error("failed to read titles.tsv at {path}: {source}")]
    Io {
        path: std::path::PathBuf,
        #[source]
        source: std::io::Error,
    },
}

/// Resolve a session title alias to a canonical UUID `sid`.
///
/// If `name` is already UUID-shaped (36-char, hyphen-delimited hex), it is
/// returned as-is without touching the file.  Otherwise `titles.tsv` is
/// searched case-insensitively, and the **first** matching `sid` is returned.
///
/// Returns `Err(AliasError::NotFound)` when no match is found — this is a hard
/// error; the caller must not silently start a fresh session.
///
/// ## Phase 0
///
/// Body is `unimplemented!()`.  Signature and error type are final.
pub fn resolve_alias(name: &str) -> Result<String, AliasError> {
    // Fast path: already a UUID — no file I/O needed.
    if looks_like_uuid(name) {
        return Ok(name.to_owned());
    }

    // Slow path: look up in titles.tsv.
    let _titles_path = paths::titles_tsv();
    unimplemented!(
        "resolve_alias: read titles.tsv, case-insensitive match on title column, \
         return first sid; hard error on miss (Phase 5 — spec N6)"
    )
}

/// Return `true` if `s` looks like a UUID — 36 characters in the
/// `xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx` pattern (all hex + hyphens at the
/// canonical positions).
///
/// This is a heuristic: it accepts any 36-char string whose positions 8, 13,
/// 18, 23 are hyphens and all other characters are ASCII hex digits.  A real
/// UUID parser would be stricter; for the alias-bypass check this is sufficient
/// and allocation-free.
///
/// This function is **always fully implemented** (pure, trivial).
pub fn looks_like_uuid(s: &str) -> bool {
    let b = s.as_bytes();
    if b.len() != 36 {
        return false;
    }
    // Hyphens at fixed positions.
    if b[8] != b'-' || b[13] != b'-' || b[18] != b'-' || b[23] != b'-' {
        return false;
    }
    // All other positions must be ASCII hex digits.
    for (i, &c) in b.iter().enumerate() {
        if i == 8 || i == 13 || i == 18 || i == 23 {
            continue; // already checked above
        }
        if !c.is_ascii_hexdigit() {
            return false;
        }
    }
    true
}

// ─── tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    // looks_like_uuid is REAL — full test coverage.

    #[test]
    fn uuid_recognised() {
        assert!(looks_like_uuid("01234567-89ab-cdef-0123-456789abcdef"));
        assert!(looks_like_uuid("aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"));
        assert!(looks_like_uuid("00000000-0000-0000-0000-000000000000"));
        assert!(looks_like_uuid("FFFFFFFF-FFFF-FFFF-FFFF-FFFFFFFFFFFF"));
    }

    #[test]
    fn non_uuid_rejected_by_length() {
        assert!(!looks_like_uuid(""));
        assert!(!looks_like_uuid("short"));
        assert!(!looks_like_uuid("01234567-89ab-cdef-0123-456789abcde")); // 35 chars
        assert!(!looks_like_uuid("01234567-89ab-cdef-0123-456789abcdeff")); // 37 chars
    }

    #[test]
    fn non_uuid_rejected_by_missing_hyphens() {
        // All hyphens replaced with 'x'
        assert!(!looks_like_uuid("01234567x89abxcdefx0123x456789abcdef"));
    }

    #[test]
    fn non_uuid_rejected_by_non_hex_in_non_hyphen_position() {
        // Replace one hex digit with 'g' (not hex)
        assert!(!looks_like_uuid("g1234567-89ab-cdef-0123-456789abcdef"));
    }

    #[test]
    fn non_uuid_rejected_when_hyphen_at_wrong_position() {
        // Move a hyphen one position left
        assert!(!looks_like_uuid("0123456-789ab-cdef-0123-456789abcdef"));
    }

    #[test]
    fn human_readable_alias_not_uuid() {
        assert!(!looks_like_uuid("my-cool-project"));
        assert!(!looks_like_uuid("latest"));
        assert!(!looks_like_uuid("some conversation about cats"));
    }

    // resolve_alias fast-path (UUID pass-through) is testable without titles.tsv.
    #[test]
    fn resolve_alias_passthrough_for_uuid() {
        let uuid = "01234567-89ab-cdef-0123-456789abcdef";
        let result = resolve_alias(uuid).expect("UUID should pass through without error");
        assert_eq!(result, uuid);
    }

    // The non-UUID (alias lookup) path is unimplemented in Phase 0 — it would
    // panic.  We verify that by checking the UUID fast-path works and leave the
    // slow path for Phase 5.
}
